### ISSUE TITLE
Accessing secrets and other step output

### ISSUE THREAD

**Issue by stefc** [pedrolamas/handlebars-action#804]
### Is your feature request related to a problem? Please describe

I want to access not only {{ env.[name] } variables but also accessing the secret store. Also I want to access output values came from previous steps. 

### Describe the solution you'd like

Inside the Template for example I store an Azure Subscription which is located in the secret store. 
I normally access it via " ${{ secrets.AZURE_SUBSCRIPTION_ID }} " this I also need inside a template. Another scenario is the access to output values from a previous step like " passwordSecretRef: ${{ steps.azure-login.outputs.TOKEN }} "

### Describe alternatives you've considered

doing some sed magic which is very tricky

**Comment by pedrolamas** [comment]
Hi @stefc, thanks for opening this ticket.

Why not pass the secret as an environment variable to the action?

```yaml
- uses: pedrolamas/handlebars-action@v2
  env:
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

With this, you would be able to use `{{ env.AZURE_SUBSCRIPTION_ID }}` as part of a template!
